// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrSQuY2AaVa3cc1GjOM53oM2lLvHKJSrA',
    appId: '1:837484925114:web:103014cc8498c818e9b283',
    messagingSenderId: '837484925114',
    projectId: 'chatapptute-f7117',
    authDomain: 'chatapptute-f7117.firebaseapp.com',
    storageBucket: 'chatapptute-f7117.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYXdaLvjf8pRQZCgJxL6mFSiar50wc6Tk',
    appId: '1:837484925114:android:5554f94ec57a0956e9b283',
    messagingSenderId: '837484925114',
    projectId: 'chatapptute-f7117',
    storageBucket: 'chatapptute-f7117.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeCQv318KQWuYFmJdQZEhjtbcoOe6GDzE',
    appId: '1:837484925114:ios:c2c2ad136aec0b18e9b283',
    messagingSenderId: '837484925114',
    projectId: 'chatapptute-f7117',
    storageBucket: 'chatapptute-f7117.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeCQv318KQWuYFmJdQZEhjtbcoOe6GDzE',
    appId: '1:837484925114:ios:913ab62e5f9a6cdae9b283',
    messagingSenderId: '837484925114',
    projectId: 'chatapptute-f7117',
    storageBucket: 'chatapptute-f7117.appspot.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
